### PR TITLE
Step 4:Added pass and check functionality

### PR DESCRIPTION
**Pull request by DhairyaShah01**
https://dhairyashah01-bluff.herokuapp.com/

Added a pass button and check button and added functionality to them to pass the turn and check whether the player bluffed or not respectively.Also, added the functionality to begin a new round when all the players have passed or when bluff is caught.

### CODE REVIEW

**Comment by pratham1002** [comment]
pass by first player in a round isn't being blocked

**Comment by Atharva-Chandak** [comment]
1. Add a check such that at least 1 card is added to stack by the player beginning the round. 
2. If all players passed, the next round begins with the player who passed last.
3. Also, as a small modification, if a bluff is caught, display a clearer message that "*Player1 caught Player2's bluff.* Adding x cards to Player2".

**Comment by Atharva-Chandak** [comment]
Nice work again @DhairyaShah01 , but this time we found @pruhnuhv's PR better organised, thus are going with that.

**Comment by apb7** [comment]
Hi @Atharva-Chandak, just curious -- why are 2 people implementing the same features/functionality?

**Comment by Atharva-Chandak** [comment]
Keeping in mind the primary end goal of the project being learning to *write better quality code*, the thought process is that we have multiple people working on same milestone so that at the end of each stage, they have a review (from us) & clear comparison as to what they could have done better (if their PR wasn't merged). Also, a little healthy competition would work well for this purpose and even promote discussions/ideas on how to implement certain features in a better way. 
Later on, after the alpha stage (i.e. after step 5 of front-end), we could have people working on different issues/features as they wish and improve the project. That is when we will also try to give them a bit of feel of how open-source *really* works.

**Pull request closed without merging**
