### PR TITLE
STEP-1 SUBMISSION

### PR DESCRIPTION
**Pull request by sarvasvaKhare**
step 1 -->https://sarvasvakhare-bluff.herokuapp.com

### CODE REVIEW

**Comment by hedonhermdev** [comment]
Hey! It’s great that you want to work on the client and the server both. But it’ll be easier for us to review your code if you make separate PR’s for each part.

**Comment by sarvasvaKhare** [comment]
The only thing changed in the client side is I added a page login.ejs with google logging button . If you want I can remove it but then you have to enter /login in url for logging in. leaving login.ejs rest of the code is same in client side. Do you want me to remove login.ejs and create a seperate pr? @hedonhermdev

**Comment by pratham1002** [comment]
@sarvasvaKhare remove login.ejs for now, login and logout buttons will be integrated in later steps as a part of main ejs file itself. The API is good, we will merge your PR after you make the change. On a side note, it is fine to skip commenting on self explanatory statements.

**Comment by sarvasvaKhare** [comment]
done requested changes @pratham1002. you could check heroku app to understand its functionality again. Thank you.

**Pull request merged**
