### PR TITLE
Step 2 - Adding Cards to Central Stack

### PR DESCRIPTION
**Pull request by DhairyaShah01**
https://dhairyashah01-bluff.herokuapp.com/

Added a click function to each card which selects the card.Also added a transfer button to transfer all the selected cards to the centralStack.Then, removed the cards moved to centralStack from the playerCards.

### CODE REVIEW

**Comment by Atharva-Chandak** [comment]
1. Using 2 functions (actualRemove & visualRemove) in seperate files to remove cards doesn't seem optimum. Have a single function doing both one after the other.
2. Add borders to selected cards. If >1 cards are selected, they become indistinguishable.
3. renderDeck itself seems a better place to add eventListeners to each cards. [This is optional]

Also, ensure that only the newly added commits are present in your PR. ( Currently, your PR has all 10 commits )

**Comment by Atharva-Chandak** [comment]
Also the transfer of cards doesn't work for more than one deck. Check it again.

**Comment by DhairyaShah01** [comment]
I have made all the changes.There was a problem in adding ids, i have resolved it.

**Comment by DhairyaShah01** [comment]
But why is it showing all the commits instead of the new ones??

**Pull request closed without merging**
